<template>
  <div class="run-page">
    <el-button link type="primary" class="back" @click="router.push('/runs')">← 返回运行记录</el-button>
    <div class="page-heading"><div><span class="eyebrow">RUN DETAIL / {{ runId }}</span><h1>运行详情</h1></div><div class="actions"><el-button v-if="canOperate && terminal" :loading="retrying" @click="retry">完整重试</el-button><el-button v-if="canOperate && terminal && failedCases" type="warning" :loading="retryingFailed" @click="retryFailed">仅重试失败用例</el-button><el-button :icon="Refresh" @click="refresh">刷新</el-button></div></div>
    <el-alert v-if="errorMessage" title="运行数据加载失败" :description="errorMessage" type="error" show-icon :closable="false" />
    <el-card v-if="run" v-loading="loading" shadow="never"><el-descriptions :column="3" border><el-descriptions-item label="Run ID">{{ run.run_id }}</el-descriptions-item><el-descriptions-item label="任务 ID">{{ run.task_id }}</el-descriptions-item><el-descriptions-item label="状态"><el-tag :type="statusTag(run.status)">{{ statusText(run.status) }}</el-tag></el-descriptions-item><el-descriptions-item label="触发方式">{{ run.trigger_type }}</el-descriptions-item><el-descriptions-item label="创建时间">{{ fmt(run.created_at) }}</el-descriptions-item><el-descriptions-item label="完成时间">{{ run.finished_at ? fmt(run.finished_at) : '-' }}</el-descriptions-item></el-descriptions></el-card>
    <el-card v-if="run" class="section" shadow="never"><template #header><strong>分片与节点</strong></template><el-table :data="run.shards" size="small"><el-table-column prop="shard_index" label="#" width="70"/><el-table-column prop="shard_id" label="Shard ID" min-width="210"/><el-table-column label="用例"><template #default="{ row }">{{ row.case_keys.join(', ') || '-' }}</template></el-table-column><el-table-column label="状态" width="120"><template #default="{ row }"><el-tag :type="statusTag(row.status)">{{ statusText(row.status) }}</el-tag></template></el-table-column><el-table-column prop="final_node" label="节点" width="150"/></el-table></el-card>
    <el-card v-if="run" class="section" shadow="never">
      <template #header><div class="card-heading"><div><strong>用例结果 × 尝试（case × attempt）</strong><span>历史失败全量保留（D-20）</span></div><el-tag effect="plain" size="small">{{ caseResults.length }} 条</el-tag></div></template>
      <el-table :data="caseResults" size="small" max-height="420">
        <el-table-column type="expand" width="44">
          <template #default="{ row }">
            <div class="case-detail">
              <div v-if="caseOutput(row, 'system-out')"><strong>print / stdout</strong><pre>{{ caseOutput(row, 'system-out') }}</pre></div>
              <div v-if="caseOutput(row, 'system-err')"><strong>logging / stderr</strong><pre>{{ caseOutput(row, 'system-err') }}</pre></div>
              <span v-if="!caseOutput(row, 'system-out') && !caseOutput(row, 'system-err')" class="muted">该 case 没有采集到独立输出</span>
            </div>
          </template>
        </el-table-column>
        <el-table-column prop="case_key" label="用例 (stable_key)" min-width="260">
          <template #default="{ row }"><div class="case-cell"><strong>{{ row.case_key }}</strong><small>{{ row.shard_id }}</small></div></template>
        </el-table-column>
        <el-table-column label="尝试 #" width="90"><template #default="{ row }"><el-tag effect="plain" size="small">#{{ row.attempt_no }}</el-tag></template></el-table-column>
        <el-table-column label="结果" width="110">
          <template #default="{ row }"><el-tag :type="caseTag(row.status)" effect="light" size="small">{{ caseText(row.status) }}</el-tag></template>
        </el-table-column>
        <el-table-column label="耗时" width="100"><template #default="{ row }">{{ row.duration_ms != null ? `${row.duration_ms}ms` : '-' }}</template></el-table-column>
        <el-table-column label="错误摘要" min-width="240">
          <template #default="{ row }"><span class="error-text">{{ row.error_summary || '-' }}</span></template>
        </el-table-column>
      </el-table>
      <el-empty v-if="caseResults.length === 0" description="暂无 case 级结果（CANoe 类任务结束后由 Agent 分析上报）" :image-size="58" />
    </el-card>
    <el-card v-if="run?.result" class="section" shadow="never"><template #header><strong>运行结果</strong></template><pre class="result">{{ prettyJson(run.result) }}</pre></el-card>
    <el-card class="section" shadow="never"><template #header><strong>执行日志</strong></template><div v-loading="logsLoading" class="log-box"><div v-for="log in logs" :key="log.sequence" class="log-line" :class="`log-${log.level}`"><span class="seq">#{{ log.sequence }}</span><span class="ts">{{ log.occurred_at ? fmt(log.occurred_at) : '-' }}</span><span>{{ log.message }}</span></div><el-empty v-if="!logsLoading && logs.length === 0" description="暂无运行日志"/></div></el-card>
    <el-card class="section" shadow="never"><template #header><strong>结束产物</strong></template><el-table :data="artifacts" size="small"><el-table-column prop="kind" label="类型" width="130"/><el-table-column prop="file_ref" label="文件" min-width="260"/><el-table-column label="大小" width="100"><template #default="{ row }">{{ formatBytes(row.size) }}</template></el-table-column><el-table-column label="操作" width="100"><template #default="{ row }"><el-button link type="primary" @click="download(row.artifact_id, row.file_ref)">下载</el-button></template></el-table-column></el-table><el-empty v-if="!artifactsLoading && artifacts.length === 0" description="暂无产物"/></el-card>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue"; import { useRouter } from "vue-router"; import { ElMessage } from "element-plus"; import { useMutation, useQuery, useQueryClient } from "@tanstack/vue-query"; import { Refresh } from "@element-plus/icons-vue"; import { aetpApi, type RunArtifact } from "@/api/endpoints"; import { useProjectStore } from "@/stores/project"; import { useAuthStore } from "@/stores/auth"; import { useTaskEvents } from "@/composables/useTaskEvents"; import { runStatusText, runStatusTag, caseStatusText, caseStatusTag } from "@/utils/statusMaps";
const props = defineProps<{ runId: string }>(); const router = useRouter(); const projectStore = useProjectStore(); const auth = useAuthStore(); const qc = useQueryClient(); useTaskEvents(qc); const projectId = computed(() => projectStore.currentProjectId ?? "");
const runQuery = useQuery({ queryKey: ["run", projectId, props.runId], queryFn: () => aetpApi.runs.get(projectId.value, props.runId), enabled: computed(() => !!projectId.value) }); const logsQuery = useQuery({ queryKey: ["run", "logs", projectId, props.runId], queryFn: () => aetpApi.runs.logs(projectId.value, props.runId), enabled: computed(() => !!projectId.value), refetchInterval: 5000 }); const artifactsQuery = useQuery({ queryKey: ["run", "artifacts", projectId, props.runId], queryFn: () => aetpApi.runs.artifacts(projectId.value, props.runId), enabled: computed(() => !!projectId.value), refetchInterval: 5000 });
const run = computed(() => runQuery.data.value ?? null); const logs = computed(() => logsQuery.data.value ?? []); const artifacts = computed(() => artifactsQuery.data.value ?? []); const loading = computed(() => runQuery.isLoading.value); const logsLoading = computed(() => logsQuery.isLoading.value); const artifactsLoading = computed(() => artifactsQuery.isLoading.value); const errorMessage = computed(() => runQuery.error.value?.message || ""); const terminal = computed(() => !!run.value && ["succeeded", "failed", "cancelled", "timed_out", "lost"].includes(run.value.status)); const canOperate = computed(() => auth.user?.platform_role === "admin" || ["operator", "maintainer", "owner"].includes(projectStore.currentRole || "")); const failedCases = computed(() => !!run.value?.result && JSON.stringify(run.value.result).includes('"failed"')); const caseResults = computed(() => run.value?.case_results ?? []);
function caseOutput(row: { detail: Record<string, unknown> | null }, key: string) { const value = row.detail?.[key]; return typeof value === "string" ? value : ""; }
const retryMutation = useMutation({ mutationFn: () => aetpApi.runs.retry(projectId.value, props.runId), onSuccess: (value) => { ElMessage.success("已创建新的重试 Run"); router.push(`/runs/${value.run_id}`); }, onError: (e: Error) => ElMessage.error(e.message) }); const retryFailedMutation = useMutation({ mutationFn: () => aetpApi.runs.retryFailed(projectId.value, props.runId), onSuccess: (value) => { ElMessage.success("已创建失败用例重试 Run"); router.push(`/runs/${value.run_id}`); }, onError: (e: Error) => ElMessage.error(e.message) }); const retrying = computed(() => retryMutation.isPending.value); const retryingFailed = computed(() => retryFailedMutation.isPending.value);
function refresh() { qc.invalidateQueries({ queryKey: ["run"] }); } function retry() { retryMutation.mutate(); } function retryFailed() { retryFailedMutation.mutate(); } function fmt(v: string) { return new Date(v).toLocaleString("zh-CN", { hour12: false }); } function prettyJson(v: unknown) { return JSON.stringify(v, null, 2); } function formatBytes(v: number) { return v < 1024 ? `${v} B` : `${(v / 1024).toFixed(1)} KB`; } async function download(id: string, name: string) { try { const blob = await aetpApi.runs.downloadArtifact(projectId.value, props.runId, id); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = name.split("/").pop() || "artifact"; a.click(); URL.revokeObjectURL(url); } catch (e) { ElMessage.error((e as Error).message); } } const statusText = runStatusText; const statusTag = runStatusTag; const caseText = caseStatusText; const caseTag = caseStatusTag;
</script>

<style scoped>.run-page { max-width:1480px; margin:0 auto; }.back { margin-bottom:12px; }.page-heading { display:flex; justify-content:space-between; align-items:flex-end; margin-bottom:22px; }.actions { display:flex; gap:8px; }.eyebrow { color:var(--aetp-cyan); font-size:10px; font-weight:800; letter-spacing:.16em; }.page-heading h1 { margin:8px 0 0; font-size:28px; }.section { margin-top:16px; }.result { margin:0; white-space:pre-wrap; font:12px monospace; }.log-box { background:#1e1e1e; border-radius:6px; padding:16px; max-height:430px; overflow:auto; font:13px monospace; min-height:100px; }.log-line { padding:5px 0; color:#ccc; border-bottom:1px solid #333; }.seq { color:#888; margin-right:10px; }.ts { color:#777; margin-right:10px; }.log-error { color:#f56c6c; }.log-warn { color:#e6a23c; }.card-heading { display:flex; align-items:center; justify-content:space-between; }.card-heading div { display:flex; align-items:baseline; gap:10px; }.card-heading strong { font-size:15px; }.card-heading span { color:var(--aetp-muted); font-size:11px; }.case-cell { display:flex; flex-direction:column; gap:2px; }.case-cell small { color:#96a3ac; font-family:ui-monospace,monospace; font-size:11px; }.case-detail { padding:12px 28px; background:#f6f8fa; }.case-detail strong { display:block; margin-bottom:5px; color:#52616b; font-size:12px; }.case-detail pre { margin:0 0 12px; white-space:pre-wrap; font:12px/1.5 ui-monospace,monospace; color:#263238; }.muted { color:#96a3ac; font-size:12px; }.error-text { color:#c45656; font-size:12px; } @media (max-width:760px) {.page-heading { align-items:flex-start; flex-direction:column; gap:14px; }.actions { flex-wrap:wrap; }}</style>
