/**
 * 向后兼容的桶文件：从 types.ts 和 api-methods.ts 重新导出所有内容。
 * 新代码建议直接 import from "@/api/types" 或 "@/api/api-methods"。
 */

// 所有接口/类型
export type {
  AdminUser,
  Device,
  EndpointCreateRequest,
  EndpointUpdateRequest,
  EventDeliveryOut,
  EventSubscriptionOut,
  HardwareChannel,
  LanguageCapability,
  LanguageRuntime,
  LoginResponse,
  ManagedPlugin,
  V2PluginVersion,
  V2CapabilitySnapshotView,
  V2DiagnosticsSnapshotView,
  V2DiagnosticsCollectResponse,
  V2PluginManifest,
  V2PluginAvailability,
  Node,
  NodeCapabilities,
  NotificationEndpointOut,
  OperatingSystem,
  Project,
  ProjectCreateRequest,
  ProjectMember,
  ProjectNodeBinding,
  ProjectUpdateRequest,
  Run,
  RunArtifact,
  RunCaseResult,
  RunDetail,
  RunEvent,
  RunLog,
  RunShard,
  ScheduleCreateRequest,
  ScheduleUpdateRequest,
  ScriptCase,
  SerialCapability,
  SerialPortCapability,
  SubscriptionCreateRequest,
  SubscriptionUpdateRequest,
  SystemCapability,
  TaskScheduleOut,
  TaskTypeConfigContext,
  TaskTypePlugin,
  TestScript,
  TestTask,
  TestTaskCreateRequest,
  UserInfo,
  VehicleBus,
  VehicleCapability,
  VehicleVendor,
} from "@/api/types";

// API 方法对象
export { aetpApi } from "@/api/api-methods";
