/**
 * API 类型与方法的统一导出入口。
 */

// 所有接口/类型
export type {
  AdminUser,
  Device,
  EndpointCreateRequest,
  EndpointUpdateRequest,
  EventDeliveryOut,
  EventSubscriptionOut,
  HardwareChannel,
  LanguageCapability,
  LanguageRuntime,
  LoginResponse,
  PluginVersion,
  PluginRef,
  Configuration,
  ScriptRef,
  TestCase,
  CaseSelection,
  SplitPolicy,
  VersionConstraint,
  RuntimeRequirement,
  SoftwareRequirement,
  ResourceRequirement,
  ExecutionRequirement,
  ScriptDefinition,
  TaskScriptRef,
  RetryPolicy,
  TestTask,
  TaskView,
  RunScriptSnapshot,
  RunSnapshot,
  RunShard,
  RunView,
  RunListView,
  RunDetailView,
  RunEventView,
  TriggerType,
  CapabilitySnapshotView,
  DiagnosticsSnapshotView,
  DiagnosticsCollectResponse,
  LogEvent,
  AgentLogView,
  RemoteOperation,
  PluginSyncView,
  LogLevelUpdateRequest,
  MaintenanceRequest,
  PluginInventoryItem,
  PluginManifest,
  PluginAvailability,
  Node,
  NodeCapabilities,
  NotificationEndpointOut,
  OperatingSystem,
  Project,
  ProjectCreateRequest,
  ProjectMember,
  ProjectNodeBinding,
  ProjectUpdateRequest,
  RunArtifact,
  ScheduleCreateRequest,
  ScheduleUpdateRequest,
  SerialCapability,
  SerialPortCapability,
  SubscriptionCreateRequest,
  SubscriptionUpdateRequest,
  SystemCapability,
  TaskScheduleOut,
  UserInfo,
  VehicleBus,
  VehicleCapability,
  VehicleVendor,
} from "@/api/types";

// API 方法对象
export { aetpApi } from "@/api/api-methods";
