"""AETP 共享协议包（P4.1，D-01）。

独立、可安装、可版本化的 Python 包（common/src/aetp_protocol），
Master / Agent / 测试工具 / CLI 复用同一契约（§4.6）。

只定义“消息是什么”，不定义“收到后怎样写库/执行/通知”：
- envelope：统一消息信封与校验（非法字段/未知类型/版本拒绝）
- message_types：消息类型枚举 + 类型↔topic 段映射
- topics：主题构建/解析/sender 身份校验（错误 topic/sender 拒绝）
- payloads：关键消息载荷 DTO
- golden：golden messages 样例（契约测试数据源）

允许：标准库、Pydantic、不可变 DTO；禁止：FastAPI/SQLAlchemy/aiomqtt/
文件路径/环境变量/线程事件循环（§4.6）。
"""

from __future__ import annotations

from .artifacts import (
    ArtifactKind,
    ArtifactRef,
    ArtifactWriteRequest,
    CaseSelection,
    Configuration,
    ConfigurationSchema,
    ScriptRef,
    TestCase,
    TestPlan,
    ValidationIssue,
)
from .authorization import (
    Action,
    AuthorizationDecision,
    AuthorizationRequest,
    AuthorizationService,
    Principal,
    ProjectScope,
    decide_project_access,
)
from .authorization import (
    PlatformRole as V2PlatformRole,
)
from .authorization import (
    ProjectRole as V2ProjectRole,
)
from .capabilities import (
    BusRequirement,
    DeviceAllocation,
    DeviceRequirement,
    HardwareChannel,
    HardwareRequirements,
    LanguageCapability,
    LanguageRequirement,
    LanguageRuntime,
    NodeCapabilities,
    NodeCapabilitySnapshot,
    NumericConstraint,
    OperatingSystem,
    OperatingSystemRequirement,
    PhysicalDeviceCapability,
    SerialCapability,
    SerialPortCapability,
    SerialPortRequirement,
    SwitchConnection,
    SwitchPort,
    SwitchRouteAllocation,
    SystemCapability,
    SystemRequirement,
    VehicleBus,
    VehicleCapability,
    VehicleRequirement,
    VehicleVendor,
    Version,
    VersionConstraint,
)
from .envelope import PROTOCOL_VERSION, Envelope, Sender, SenderKind
from .errors import (
    InvalidSenderError,
    MessagePayloadError,
    ProtocolError,
    ProtocolVersionMismatchError,
    TopicMismatchError,
)
from .execution import (
    AttemptStatus,
    CaseResult,
    CaseStatus,
    ExecutionError,
    ExecutionPlan,
    ExecutionRequirement,
    ExecutionResult,
    ExecutionStatus,
    LeaseState,
    NodePresenceState,
    PlanResourceBinding,
    ResourceLease,
    RunStatus,
    ShardStatus,
)
from .ids import (
    BusinessId,
    CapabilityName,
    JsonObject,
    JsonValue,
    MessageId,
    PluginId,
    RelativePath,
    RequestId,
    SemVer,
    SessionId,
    Sha256,
    TraceId,
    VersionRange,
    new_id,
    new_ulid,
)
from .ids import (
    VersionConstraint as V2VersionConstraint,
)
from .logs import AgentLogBatch, LogCode, LogEvent, LogLevel, RunLogBatch, RunLogEntry
from .message_types import MessageType
from .payloads import (
    CaseResultEntry,
    CaseStatusEvent,
    DiagnosticsRequest,
    DiagnosticsSnapshot,
    ExecutionAck,
    ExecutionCancel,
    ExecutionFinished,
    ExecutionProgress,
    Heartbeat,
    NodeRegister,
    NodeRegisterAck,
    PluginPackageRef,
    Presence,
    RegisterAckPayload,
    RunCancelPayload,
    RunCaseStatusPayload,
    RunLogCompletePayload,
    RunProgressPayload,
    RunResultPayload,
    ScriptParsePayload,
    ScriptParseResultPayload,
    ScriptVerifyPayload,
    ScriptVerifyResultPayload,
)
from .plugin import (
    AgentExecutionPlugin,
    AgentPackageSpec,
    AgentTaskContext,
    CaseInfo,
    PluginMetadata,
    PluginPackage,
    ShardSpec,
    TaskDefinitionSpec,
)
from .plugin_types import (
    PluginAvailability,
    PluginDistributionRef,
    PluginPoint,
    PluginRef,
    PluginStatus,
    PluginSyncAction,
)
from .plugins import (
    EntrypointRef,
    PluginEntrypoints,
    PluginManifest,
    PluginSyncItem,
    PluginSyncItemResult,
    PluginSyncRequest,
    PluginSyncResult,
    StaticRequirements,
)
from .topics import (
    TopicInfo,
    command_topic,
    event_topic,
    parse_topic,
    parse_v2_topic,
    v2_command_topic,
    v2_event_topic,
    validate_message_type_for_topic,
    validate_message_type_for_v2_topic,
    validate_sender_for_topic,
    validate_sender_for_v2_topic,
)
from .v2_envelope import V2_PROTOCOL_VERSION, V2Envelope, V2Sender, parse_v2_message

__all__ = [
    "PROTOCOL_VERSION",
    "Action",
    "AgentExecutionPlugin",
    "AgentPackageSpec",
    "AgentTaskContext",
    "AgentLogBatch",
    "ArtifactKind",
    "ArtifactRef",
    "ArtifactWriteRequest",
    "AttemptStatus",
    "AuthorizationDecision",
    "AuthorizationRequest",
    "AuthorizationService",
    "BusRequirement",
    "BusinessId",
    "CapabilityName",
    "CaseInfo",
    "CaseResult",
    "CaseResultEntry",
    "CaseStatusEvent",
    "CaseSelection",
    "CaseStatus",
    "Configuration",
    "ConfigurationSchema",
    "DeviceAllocation",
    "DeviceRequirement",
    "Envelope",
    "EntrypointRef",
    "ExecutionError",
    "ExecutionAck",
    "ExecutionCancel",
    "ExecutionFinished",
    "ExecutionPlan",
    "ExecutionProgress",
    "ExecutionRequirement",
    "ExecutionResult",
    "ExecutionStatus",
    "HardwareChannel",
    "HardwareRequirements",
    "InvalidSenderError",
    "JsonObject",
    "JsonValue",
    "LeaseState",
    "LogCode",
    "LogEvent",
    "LanguageCapability",
    "LanguageRequirement",
    "LanguageRuntime",
    "LogLevel",
    "MessageType",
    "MessageId",
    "MessagePayloadError",
    "NodeCapabilities",
    "NodeCapabilitySnapshot",
    "NodePresenceState",
    "NodeRegister",
    "NodeRegisterAck",
    "Heartbeat",
    "Presence",
    "DiagnosticsRequest",
    "DiagnosticsSnapshot",
    "NumericConstraint",
    "OperatingSystem",
    "OperatingSystemRequirement",
    "PhysicalDeviceCapability",
    "PluginId",
    "PluginMetadata",
    "PluginManifest",
    "PluginEntrypoints",
    "PluginPackage",
    "PluginPackageRef",
    "PluginRef",
    "PluginDistributionRef",
    "PluginPoint",
    "PluginAvailability",
    "PluginStatus",
    "PluginSyncAction",
    "PluginSyncItem",
    "PluginSyncItemResult",
    "PluginSyncRequest",
    "PluginSyncResult",
    "ProtocolError",
    "ProtocolVersionMismatchError",
    "RegisterAckPayload",
    "RunCancelPayload",
    "RunCaseStatusPayload",
    "RunLogBatch",
    "RunLogCompletePayload",
    "RunLogEntry",
    "RunProgressPayload",
    "RunResultPayload",
    "RunStatus",
    "RelativePath",
    "RequestId",
    "ResourceLease",
    "PlanResourceBinding",
    "ProjectScope",
    "Principal",
    "ScriptRef",
    "SemVer",
    "SessionId",
    "Sha256",
    "ShardStatus",
    "StaticRequirements",
    "TestCase",
    "TestPlan",
    "TraceId",
    "ValidationIssue",
    "V2Envelope",
    "V2_PROTOCOL_VERSION",
    "V2PlatformRole",
    "V2ProjectRole",
    "V2Sender",
    "V2VersionConstraint",
    "VersionRange",
    "ScriptParsePayload",
    "ScriptParseResultPayload",
    "ScriptVerifyPayload",
    "ScriptVerifyResultPayload",
    "Sender",
    "SenderKind",
    "SerialCapability",
    "SerialPortCapability",
    "SerialPortRequirement",
    "ShardSpec",
    "SwitchConnection",
    "SwitchPort",
    "SwitchRouteAllocation",
    "SystemCapability",
    "SystemRequirement",
    "TaskDefinitionSpec",
    "TopicInfo",
    "TopicMismatchError",
    "VehicleBus",
    "VehicleCapability",
    "VehicleRequirement",
    "VehicleVendor",
    "Version",
    "VersionConstraint",
    "command_topic",
    "event_topic",
    "new_id",
    "new_ulid",
    "parse_topic",
    "parse_v2_message",
    "parse_v2_topic",
    "decide_project_access",
    "validate_message_type_for_topic",
    "validate_message_type_for_v2_topic",
    "validate_sender_for_topic",
    "validate_sender_for_v2_topic",
    "v2_command_topic",
    "v2_event_topic",
]
