"""AETP 共享协议包（P4.1，D-01）。

独立、可安装、可版本化的 Python 包（common/src/aetp_protocol），
Master / Agent / 测试工具 / CLI 复用同一契约（§4.6）。

只定义“消息是什么”，不定义“收到后怎样写库/执行/通知”：
- envelope：统一消息信封与校验（非法字段/未知类型/版本拒绝）
- message_types：消息类型枚举 + 类型↔topic 段映射
- topics：主题构建/解析/sender 身份校验（错误 topic/sender 拒绝）
- payloads：关键消息载荷 DTO
- golden：golden messages 样例（契约测试数据源）

允许：标准库、Pydantic、不可变 DTO；禁止：FastAPI/SQLAlchemy/aiomqtt/
文件路径/环境变量/线程事件循环（§4.6）。
"""

from __future__ import annotations

from .artifacts import (
    ArtifactKind,
    ArtifactRef,
    ArtifactWriteRequest,
    CaseSelection,
    Configuration,
    ConfigurationSchema,
    ScriptRef,
    TestCase,
    TestPlan,
    ValidationIssue,
)
from .authorization import (
    Action,
    AuthorizationDecision,
    AuthorizationRequest,
    AuthorizationService,
    Principal,
    ProjectScope,
    decide_project_access,
)
from .authorization import (
    PlatformRole as PlatformRole,
)
from .authorization import (
    ProjectRole as ProjectRole,
)
from .capabilities import (
    AgentMaintenanceState,
    BusRequirement,
    DeviceAllocation,
    DeviceRequirement,
    HardwareChannel,
    HardwareRequirements,
    LanguageCapability,
    LanguageRequirement,
    LanguageRuntime,
    NodeCapabilities,
    NodeCapabilitySnapshot,
    NumericConstraint,
    OperatingSystem,
    OperatingSystemRequirement,
    PhysicalDeviceCapability,
    PluginInventoryItem,
    ResourceCapability,
    ResourceHealth,
    RuntimeCapability,
    SerialCapability,
    SerialPortCapability,
    SerialPortRequirement,
    SoftwareCapability,
    SwitchConnection,
    SwitchPort,
    SwitchRouteAllocation,
    SystemCapability,
    SystemRequirement,
    VehicleBus,
    VehicleCapability,
    VehicleRequirement,
    VehicleVendor,
    Version,
)
from .envelope import PROTOCOL_VERSION, Envelope, Sender, SenderKind, parse_message
from .errors import (
    InvalidSenderError,
    MessagePayloadError,
    ProtocolError,
    ProtocolVersionMismatchError,
    TopicMismatchError,
)
from .execution import (
    AttemptStatus,
    CaseResult,
    CaseStatus,
    ExecutionError,
    ExecutionPlan,
    ExecutionRequirement,
    ExecutionResult,
    ExecutionStatus,
    LeaseState,
    NodePresenceState,
    PlanResourceBinding,
    ResourceBinding,
    ResourceInfo,
    ResourceLease,
    ResourceRequirement,
    RunStatus,
    RuntimeBinding,
    RuntimeInfo,
    RuntimeRequest,
    RuntimeRequirement,
    RuntimeSelection,
    ShardStatus,
    SoftwareRequirement,
)
from .ids import (
    BusinessId,
    CapabilityName,
    JsonObject,
    JsonValue,
    MessageId,
    PluginId,
    RelativePath,
    RequestId,
    SemVer,
    SessionId,
    Sha256,
    TraceId,
    VersionRange,
    new_id,
    new_ulid,
    stable_id,
)
from .ids import (
    VersionConstraint as VersionConstraint,
)
from .logs import AgentLogBatch, LogCode, LogEvent, LogLevel, RunLogBatch, RunLogEntry
from .message_types import MessageType
from .payloads import (
    AgentLogReceived,
    CaseStatusEvent,
    DiagnosticsRequest,
    DiagnosticsSnapshot,
    ExecutionAck,
    ExecutionCancel,
    ExecutionFinished,
    ExecutionProgress,
    ExecutionReconcileResult,
    Heartbeat,
    LogLevelUpdateRequest,
    LogLevelUpdateResult,
    MaintenanceDrainRequest,
    MaintenanceDrainResult,
    MaintenanceRestartRequest,
    MaintenanceRestartResult,
    MaintenanceStatus,
    NodeRegister,
    NodeRegisterAck,
    Presence,
    RemoteOperation,
    RemoteOperationStatus,
)
from .plan_hash import calculate_plan_hash, canonical_plan_document, with_plan_hash
from .plugin_types import (
    DesiredPluginVersion,
    PluginAvailability,
    PluginDistributionRef,
    PluginPoint,
    PluginRef,
    PluginStatus,
    PluginSyncAction,
)
from .plugins import (
    EntrypointRef,
    PluginEntrypoints,
    PluginManifest,
    PluginSyncItem,
    PluginSyncItemResult,
    PluginSyncRequest,
    PluginSyncResult,
    StaticRequirements,
)
from .reporting import (
    AnalysisRequest,
    AnalysisResult,
    AnalyzerPlugin,
    DeliveryResult,
    DeliveryStatus,
    NotificationPolicy,
    NotificationRequest,
    NotifierPlugin,
    PluginContext,
    ReporterPlugin,
    ReportRequest,
    ReportResult,
    UnifiedTestResult,
)
from .resource import (
    ResourceActivationError,
    ResourceDiscoveryError,
    ResourceProvider,
    ResourceProviderError,
)
from .task import RunScriptSnapshot, RunSnapshot, ScriptDefinition, TaskScriptRef, TestRun, TestTask
from .topics import (
    TopicInfo,
    command_topic,
    event_topic,
    parse_topic,
    validate_message_type_for_topic,
    validate_sender_for_topic,
)

__all__ = [
    "PROTOCOL_VERSION",
    "Action",
    "AgentLogBatch",
    "AgentLogReceived",
    "ArtifactKind",
    "ArtifactRef",
    "ArtifactWriteRequest",
    "AgentMaintenanceState",
    "AttemptStatus",
    "AuthorizationDecision",
    "AuthorizationRequest",
    "AuthorizationService",
    "AnalysisRequest",
    "AnalysisResult",
    "AnalyzerPlugin",
    "BusRequirement",
    "BusinessId",
    "CapabilityName",
    "CaseResult",
    "CaseStatusEvent",
    "CaseSelection",
    "CaseStatus",
    "calculate_plan_hash",
    "canonical_plan_document",
    "Configuration",
    "ConfigurationSchema",
    "DeviceAllocation",
    "DeviceRequirement",
    "Envelope",
    "EntrypointRef",
    "ExecutionError",
    "ExecutionAck",
    "ExecutionCancel",
    "ExecutionFinished",
    "ExecutionPlan",
    "ExecutionProgress",
    "ExecutionReconcileResult",
    "ExecutionRequirement",
    "ExecutionResult",
    "ExecutionStatus",
    "HardwareChannel",
    "HardwareRequirements",
    "InvalidSenderError",
    "JsonObject",
    "JsonValue",
    "LeaseState",
    "LogCode",
    "LogEvent",
    "LanguageCapability",
    "LanguageRequirement",
    "LanguageRuntime",
    "LogLevel",
    "MessageType",
    "MessageId",
    "MessagePayloadError",
    "MaintenanceStatus",
    "NodeCapabilities",
    "NodeCapabilitySnapshot",
    "PluginInventoryItem",
    "NodePresenceState",
    "NodeRegister",
    "NodeRegisterAck",
    "NotificationPolicy",
    "NotificationRequest",
    "NotifierPlugin",
    "Heartbeat",
    "Presence",
    "DiagnosticsRequest",
    "DiagnosticsSnapshot",
    "DeliveryResult",
    "DeliveryStatus",
    "LogLevelUpdateRequest",
    "LogLevelUpdateResult",
    "MaintenanceDrainRequest",
    "MaintenanceDrainResult",
    "MaintenanceRestartRequest",
    "MaintenanceRestartResult",
    "RemoteOperation",
    "RemoteOperationStatus",
    "DesiredPluginVersion",
    "NumericConstraint",
    "OperatingSystem",
    "OperatingSystemRequirement",
    "PhysicalDeviceCapability",
    "ResourceBinding",
    "ResourceActivationError",
    "ResourceCapability",
    "ResourceDiscoveryError",
    "ResourceProvider",
    "ResourceProviderError",
    "ResourceHealth",
    "ResourceInfo",
    "ResourceRequirement",
    "PluginId",
    "PluginContext",
    "PluginManifest",
    "PluginEntrypoints",
    "PluginRef",
    "PluginDistributionRef",
    "PluginPoint",
    "PluginAvailability",
    "PluginStatus",
    "PluginSyncAction",
    "PluginSyncItem",
    "PluginSyncItemResult",
    "PluginSyncRequest",
    "PluginSyncResult",
    "ProtocolError",
    "ProtocolVersionMismatchError",
    "RunLogBatch",
    "RunLogEntry",
    "RunScriptSnapshot",
    "RunSnapshot",
    "RunStatus",
    "RuntimeBinding",
    "RuntimeCapability",
    "RuntimeInfo",
    "RuntimeRequest",
    "RuntimeRequirement",
    "RuntimeSelection",
    "RelativePath",
    "RequestId",
    "ResourceLease",
    "PlanResourceBinding",
    "ProjectScope",
    "Principal",
    "ScriptRef",
    "ScriptDefinition",
    "SemVer",
    "SessionId",
    "Sha256",
    "stable_id",
    "ShardStatus",
    "SoftwareCapability",
    "SoftwareRequirement",
    "StaticRequirements",
    "TestCase",
    "TestRun",
    "TestTask",
    "TestPlan",
    "TaskScriptRef",
    "TraceId",
    "ReporterPlugin",
    "ReportRequest",
    "ReportResult",
    "UnifiedTestResult",
    "ValidationIssue",
    "Envelope",
    "PROTOCOL_VERSION",
    "PlatformRole",
    "ProjectRole",
    "Sender",
    "VersionRange",
    "Sender",
    "SenderKind",
    "SerialCapability",
    "SerialPortCapability",
    "SerialPortRequirement",
    "SwitchConnection",
    "SwitchPort",
    "SwitchRouteAllocation",
    "SystemCapability",
    "SystemRequirement",
    "TopicInfo",
    "TopicMismatchError",
    "VehicleBus",
    "VehicleCapability",
    "VehicleRequirement",
    "VehicleVendor",
    "Version",
    "VersionConstraint",
    "command_topic",
    "event_topic",
    "new_id",
    "new_ulid",
    "parse_topic",
    "parse_message",
    "decide_project_access",
    "validate_message_type_for_topic",
    "validate_sender_for_topic",
    "with_plan_hash",
]
